import { getSessionUser } from '../../utils/session'
import { searchExerciseTemplates } from '../../utils/exercise-search'

/**
 * Catalogue search for the plan editor's exercise picker.
 *
 * Deliberately the same `searchExerciseTemplates()` the AI generator calls: a
 * plan typed by hand and a plan generated by the model must resolve names to
 * ids by identical rules, or the two produce different `exercise_template_id`s
 * for the same movement and only one of them pushes to Hevy.
 */
export default defineEventHandler(async (event) => {
  const { id: userId } = await getSessionUser(event)
  const q = getQuery(event)

  return searchExerciseTemplates(userId, {
    query: typeof q.query === 'string' ? q.query : undefined,
    muscle_group: typeof q.muscle_group === 'string' ? q.muscle_group : undefined,
    equipment: typeof q.equipment === 'string' ? q.equipment : undefined,
    limit: q.limit ? Number(q.limit) : undefined
  })
})
